"""create categories table

Revision ID: 1666ca00245d
Revises: 94b452eadce6
Create Date: 2026-06-12 23:47:38.570298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1666ca00245d'
down_revision: Union[str, Sequence[str], None] = '94b452eadce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['id'])
    op.drop_column('services', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
